### ISSUE TITLE
Micromouse buy

### ISSUE THREAD

**Issue by volkankoc** [lime7git/micromouse#3]
Where is the sale this micromouse robot ?
Buy link ? or contact address

**Comment by lime7git** [comment]
@volkankoc 
> Where is the sale this micromouse robot ? Buy link ? or contact address

Hi, I am afraid that it is not possible at this moment. It is only my master's degree thesis project which I am still working on. If You have any questions feel free to contact me on Twitter @BugajskiEmil.
